#Generated by Arduino Maestro (ChatGPT explore GPT's)
import serial
import time
from pynput.keyboard import Controller as KeyboardController
from pynput.mouse import Button, Controller as MouseController

# Initialize serial communication
ser = serial.Serial('COM8', 9600)
keyboard = KeyboardController()
mouse = MouseController()

# Mouse sensitivity
mouse_sensitivity = 3 # Change this value to adjust sensitivity

# Function to press keys and perform mouse movements
def press_keys(keys):
    for key in keys:
        if key == 'R':
            # mouse.click(Button.right, 1)  # Perform a right click
            press_keys(" ")
        elif key == 'L':
            mouse.click(Button.left, 1)   # Perform a left click
        elif key == 'i':
            mouse.move(0, -10 * mouse_sensitivity)  # Move mouse up
        elif key == 'j':
            mouse.move(-10 * mouse_sensitivity, 0)  # Move mouse left
        elif key == 'k':
            mouse.move(0, 10 * mouse_sensitivity)   # Move mouse down
        elif key == 'l':
            mouse.move(10 * mouse_sensitivity, 0)   # Move mouse right
        else:
            keyboard.press(key)

    time.sleep(0.1)  # Adjusted sleep time for smoother operation

    for key in keys:
        if key not in ('R', 'L', 'i', 'j', 'k', 'l'):
            keyboard.release(key)
            keyboard.release(" ")

try:
    buffer = ""
    while True:
        if ser.in_waiting > 0:
            buffer += ser.read(ser.in_waiting).decode('utf-8')
            while '\n' in buffer:
                line, buffer = buffer.split('\n', 1)
                line = line.rstrip()
                if line:
                    press_keys(line)
except KeyboardInterrupt:
    ser.close()
